language: node_js
node_js:
  - "6"
  - "14"

# Disable npm cache to make npm ci work reliably
# See https://travis-ci.community/t/npm-ci-will-fail-if-cached-dependency-includes-npm/4203/2
cache:
  npm: false

install:
  - npm ci
  - npm run bower -- install

script:
  - npm run build
  - npm run test
  - npm run coveralls
