language: node_js
node_js:
  - "8"
before_install:
  - gem install compass
  - npm install -g npm@2
  - npm install -g grunt-cli bower
install:
  - npm install
  - bower install
script: grunt && grunt test && grunt coveralls