language: node_js
node_js:
  - "6"
  - "14"

before_install:
  - gem install compass

install:
  - npm install
  - npm run bower -- install

script:
  - npm run build
  - npm run test
  - npm run coveralls
