language: node_js
node_js:
  - "6"
  - "14"

# Disable npm cache to make npm ci work reliably
# See https://travis-ci.community/t/npm-ci-will-fail-if-cached-dependency-includes-npm/4203/2
cache:
  npm: false

before_install:
  - gem install compass
  - npm install -g npm@6.9.0
  - npm install -g grunt@1.0.3 grunt-cli@1.2.0
  - npm install -g bower

install:
  - npm ci
  - bower install

script:
  - grunt --version
  - grunt
  - grunt test
  - grunt coveralls
