version: "3.5"

services:

  node:
    build: docker/node
    hostname: 'projectaanvraag-frontend.local'
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    container_name: node.projectaanvraag
    ports:
      - '9999:9999'
    networks:
      - projectaanvraag

networks:
  projectaanvraag:
    driver: bridge
